name: FindWindowsUpdates
on:
  push:
    branches: 
    - main
jobs:
  findWindowsUpdates:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Get list of existing updates
        run: Get-Content .\existingUpdates.txt
      
      - name: Install Windows Module "MSCatalog"
        run: Install-Module MSCatalog -Scope CurrentUser -Force -Verbose
        
      - name: Search for latest windows updates
        run: | 
          Get-Content .\existingUpdates.txt | foreach-object {
              echo "`n Search Result for $_ `n"
              Get-MSCatalogUpdate -Search $_
          }
          
      - name: Search and Show for latest windows updates for server 2016 and 2019 and Win10Pro
        run: | 
          echo "***************************************************"
          echo "** Updates Available for Windows Server 2016 x64 **"
          echo "***************************************************"

          $Updates2016 = Get-MSCatalogUpdate -Search "Cumulative Update for Windows Server 2016 for x64-based Systems" | `
          ?{($_.products -like "*Windows Server 2016*") -and ($_.title -notlike "*Preview*") }
          $Updates2016 | select Title, LastUpdated, Size, Classification -First 5
          Save-MSCatalogUpdate -Update $Updates2019[0] -Destination ".\"

          echo ""
          echo "***************************************************"
          echo "** Updates Available for Windows Server 2019 x64 **"
          echo "***************************************************"

          $Updates2019 = Get-MSCatalogUpdate -Search "Cumulative Update for Windows Server 2019 for x64-based Systems" | `
          ?{($_.products -like "*Windows Server 2019*") -and ($_.title -notlike "*Preview*") }
          $Updates2019 | select Title, LastUpdated, Size, Classification -First 5
          Save-MSCatalogUpdate -Update $Updates2019[0] -Destination ".\"

          echo ""
          echo "***************************************************"
          echo "** Updates Available for Windows10Pro 20H2 1903+ **"
          echo "***************************************************"

          $UpdatesWin10 = Get-MSCatalogUpdate -Search "Cumulative Update for Windows 10 Version 20H2 for x64-based Systems" | `
          ?{($_.products -like "*Windows 10, version 1903*") -and ($_.title -notlike "*Preview*") }
          $UpdatesWin10 | select Title, LastUpdated, Size, Classification -First 5
          Save-MSCatalogUpdate -Update $Updates2019[0] -Destination ".\"
      
      - name: Download azcopy.exe 
        run: | 
          ls
          Invoke-WebRequest -Uri "https://aka.ms/downloadazcopy-v10-windows" -OutFile AzCopy.zip -UseBasicParsing
          Expand-Archive .\AzCopy.zip .\AzCopy -Force
          Get-ChildItem ./AzCopy/*/azcopy.exe | Move-Item -Destination .
          ls
          .\azcopy.exe --help
      
      - name: Upload msu files to Azure blob
        run: | 
          Write-Output "upload the msu files to blob"
          & .\azcopy.exe copy *.msu "${{ secrets.BLOB_CONTAINER_URI }}?${{ secrets.SAS_TOKEN }}" --overwrite=true
          if ($?) { Write-Output "Logfile upload successful" }
