name: FindWindowsUpdates
on:
  push:
    branches: 
    - main
jobs:
  findWindowsUpdates:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: Get list of existing updates
        run: Get-Content .\existingUpdates.txt
      
      - name: Install Windows Module "MSCatalog"
        run: Install-Module MSCatalog -Scope CurrentUser -Force -Verbose
        
      - name: Search for latest windows updates
        run: | 
          Get-Content .\existingUpdates.txt | foreach-object {
              echo "`n Search Result for $_ `n"
              Get-MSCatalogUpdate -Search $_
          }
          
      - name: Search and download for latest windows updates for server 2016 and 2019
        run: | 
          Get-MSCatalogUpdate -Search "Cumulative Update for Windows Server 2019 for x64-based Systems" | ?{$_.products -like "*Windows Server 2019*"} | select Title, Classification, LastUpdated
          $Updates2019 = Get-MSCatalogUpdate -Search "Cumulative Update for Windows Server 2019 for x64-based Systems" | ?{$_.products -like "*Windows Server 2019*"}
          Save-MSCatalogUpdate -Update $Updates2019[0] -Destination ".\"
          ls
      
      - name: Download azcopy.exe 
        run: | 
          Invoke-WebRequest -Uri "https://aka.ms/downloadazcopy-v10-windows" -OutFile AzCopy.zip -UseBasicParsing
          Expand-Archive .\AzCopy.zip .\AzCopy -Force
          Get-ChildItem ./AzCopy/*/azcopy.exe | Move-Item -Destination .
          .\azcopy.exe --help
